### ISSUE TITLE
Improve documentation surrounding registerMock();

### ISSUE THREAD

**Issue by KevinMind** [Typescript-TDD/ts-auto-mock#762] opened 2021-05-28 09:51 UTC
### Subject of the issue

I'm setting up ts-auto-mock to use in jest with registerMock<> being an important component.

We want to be able to mock interfaces for react components, and other data objects in our jest tests and setup sensible default values beyond what ts-auto-mock natively provides.

For example, where a simple string pattern does not suffice. We care about specific values sometimes.

```tsx
interface MoneyObject {
   amount: number;
   currencyCode: 'USD' | 'EUR';
```
When trying to set this behaviour up we might imagine a test looking like.

money.test.ts
```ts
import {createMock} from 'ts-auto-mock';
import {MoneyObject} from 'types';

test('money', () => {
   const mock = createMock<MoneyObject>();
   
   expect(['USD', 'EUR'].includes(mock.currencyCode)).toEqual(true);
});
```

If we setup ts-auto-mock with or without the randomization feature it will fail as the value of `mock.currencyCode` would equal something like `money3sdflkj`.

So we use `registerMock<MoneyObject>` to create a more usable mock.
This "kind of" works, but I'm getting some very strange behaviour that I do not understand and do not know how to consistently fix.

Let's set up the registered mock.

money.mock.ts
```ts
import faker from 'faker';
import {registerMock} from 'ts-auto-mock';
import {MoneyObject} from 'types';
import {Currencies} from 'money';

registerMock<MoneyObject>(() => ({
   amount: faker.random.number(),
   currencyCode: Currencies.USD,
});
```

This file defines our mock factory and maps it to the MoneyObject.. makes sense so far.
But how am I supposed to inject this file? It is basically a "Side-effect" script file so I was thinking to either:

1. import this file in any test that wants to mock `MoneyObject`. This is nice to be explicit and composable about which mocks are available when. (THIS WORKS SOMETIMES, but other times throws errors).
2. import in setup.js file for jest, so all mocks are registered very early. (THIS DID NOT WORK AT ALL)

If you look at the documentation you will see a note

`Note: You can only use it in a common file (webpack context.ts, mocha tsnode.js, etc), using registerMock in other files will give unexpected results.`

I think I am getting these "unexpected" results. But I do not understand why.. So I would like help understanding this, and potentially could create a PR to improve the documentation once I do? Maybe add some examples. I'm happy to contribute to improve the experience for others.

### Your environment

    "ts-auto-mock": "^3.1.3",
    "ts-jest": "^26.5.5",
    "ttypescript": "^1.5.12",
    "typescript": "^4.1.5"

* node version: 12.17.0
* npm version: yarn 1.22.0

* list any other dependencies that you think are relevant

    "faker": "^4.1.0",

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a test code example.

1. try importing the money.mock.ts file in the test file, then also try importing in setup.js file for jest. In the 1st scenario, the mock is created successfully. but when you are importing other mock files, and registering mocks in multiple files, as mentioned "weird" things happen.

2. try importing the registerMock file(s) in setup.js. In my experience the modules are loaded, but the mocks use the default method instead of the registered mock method for creating data.

### Expected behavior

I should have a money object with currencyCode: 'USD'

### Actual behavior

I get 'currencyCode234'

**Comment by Pmyl** [comment] 2021-05-28 16:43
The random string is a bug, it doesn't adhere with the interface so that shouldn't happen... I'll take some time to investigate a fix in the next days.

Without the random it should choose the first string, if it doesn't do that it's another bug, I'm not at my pc, I'll check later

For the registerMock I'm not sure so I want to summon @uittorio . I can tell you that you're right, it's a "side effect", it registers the provided mock so that when you run a createMock with that interface it spits out your provided one. It should work if you put it in the main file (the one usually used to define common functionalities across all tests) but I'm not an expert in jest. One thing I can say is that if you included it in setup.**js** then it's probably the wrong file, the file has to be a typescript file so that the transformer can pick it up. @uittorio can help on this better than me though

**Comment by uittorio** [comment] 2021-05-28 18:58
Hi! 

So, what about registerMock,

Short answer, in jest you have to use it in every file and make sure you have the cache disabled! If that doesnt work there is a bug 😅 .

Can you provide the transformer configuration? 

Why can you not just import the register mock in one file!?
Jest runs the tests independently and we currently register the mock in the test file itself making impossible (sometimes) for jest to find the mock.
We've investigated different approaches where we store the register mock in different files but we haven't completed that work yet! 

@Pmyl I think we don't convert string literals properly, that is a shame!

**Comment by Pmyl** [comment] 2021-05-28 20:37
I'm at my PC and I have some results.
I tried this test:
```ts
interface A {
  a: string;
  b: 'Test' | 'What';
}

it('should work for string', () => {
  const mock: A = createMock<A>();
  expect(mock.a).toBe('');
});

it('should work for string literal', () => {
  const mock: A = createMock<A>();
  expect(mock.b).toBe('Test');
});
```

Without `random` everything passes
![image](https://user-images.githubusercontent.com/16228209/120039310-9a84f280-bffc-11eb-93a8-3549c1e44375.png)

With `random`, as expected, the test on property `a` fails because it's a random string but the test on property `b` passes correctly
![image](https://user-images.githubusercontent.com/16228209/120039393-ba1c1b00-bffc-11eb-8ea6-0cc13ed09db3.png)


I don't understand why my result is different than yours @KevinMind , could you create a repo with a reproduction of this bug?

**Comment by Pmyl** [comment] 2021-06-17 14:55
@KevinMind I couldn't reproduce the main bug, if you have a reproduction of the bug that I can use or if you have other questions let us know, otherwise I'll close this bug 😄

**Comment by uittorio** [comment] 2021-08-30 11:47
Time to close this bug, @KevinMind feel free to open it again if you more informations!

**Closed by uittorio** 2021-08-30 11:47 UTC
